services:
  - type: web
    name: edutrack-pro
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate && npx prisma migrate deploy
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        value: https://edutrack-pro.onrender.com
      - key: NEXTAUTH_SECRET
        generateValue: true
